### ISSUE TITLE
multiple correction whole brain

### ISSUE THREAD

**Issue by vogab** [hyemin-han/BayesFactorFMRI_TWOT#2]
Hi,

I have a few questions about multiple comparison in your package. I am wondering if it is strictly equivalent to FWE voxelwise correction? In which case, it still be a rather conservative correction compared to cluster based correction.

Do you know of a way to get an equivalence between a certain p threshold and BF threshold. Let's say that I would like to try to make bayesian analysis comparable to to a p threshold of 0.05, 0.01, 0.001. Can I find the BF threshold that correspond to these p values? And does this approach make sense?

I was wondering about this paper:
Han, H. (2020). Implementation of Bayesian multiple comparison correction in the second-level analysis of fMRI data: With pilot analyses of simulation and real fMRI datasets based on voxelwise inference. Cognitive neuroscience, 11(3), 157-169.

Are all you reanalyzes of real data based on ROI?

What do you think of the applicability of you method to full brain analysis, with ROIs?

**Comment by hyemin-han** [comment]
I am going to say that Bayes Factors could not be strictly equivalent to certain p-values since Bayesian analysis is based on a totally different set of philosophical grounds vs. frequentist test. Depending on which priors you use, which data you analyze, etc. the relationship between BFs and p-values can significantly vary. So, I do not recommend you try to equate BFs = p-values. If you are curious about further details, I would like you to read some papers addressing the philosophy + practical stuff of Bayesian analysis, such as:

Wagenmakers, E. J., Marsman, M., Jamil, T., Ly, A., Verhagen, J., Love, J., ... & Morey, R. D. (2018). Bayesian inference for psychology. Part I: Theoretical advantages and practical ramifications. Psychonomic bulletin & review, 25, 35-57.
Wagenmakers, E. J., Love, J., Marsman, M., Jamil, T., Ly, A., Verhagen, J., ... & Morey, R. D. (2018). Bayesian inference for psychology. Part II: Example applications with JASP. Psychonomic bulletin & review, 25, 58-76.

In my prior paper, I conducted the whole-brain analysis. However, the same procedures can be applicable to ROI-based analysis as well.
